{
 "title": "basic",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_echo_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx/3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(app_echo_requests_total{code=~'[2-3]..'}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(app_echo_requests_total{code=~'4..'}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(app_echo_requests_total{code=~'5..'}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_echo_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95%ile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(app_echo_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90%ile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(app_echo_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50%ile"
    }
   ]
  },
  { "title": "go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "app logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{compose_service=\"app\"} |= ``"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "virtual" }
   ]
  },
  {
   "title": "go memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "bytes allocated" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])",
     "legendFormat": "alloc rate"
    },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "stack inuse" },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "heap inuse" }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
   ]
  },
  { "title": "k6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(k6_http_reqs_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(k6_http_reqs_total{expected_response=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "k6 logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 42 },
   "targets": [
    {
     "expr": "{qa=\"k6\"} |= ``"
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    { "expr": "sum(k6_vus)", "legendFormat": "vus" },
    {
     "expr": "avg(k6_http_req_duration_seconds)",
     "legendFormat": "http_req_duration_seconds"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  }
 ]
}