global:
  resolve_timeout: 5m

route:
    receiver: 'my_alert'

receivers:
    - name: 'my_alert'
      webhook_configs:
      - url: http://host.docker.internal:8882/noti # replace with your PagerTree webhook url